/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

/**
 *
 * @author giuse
 */
public class AtomAskingWindow extends javax.swing.JDialog {
    
    private Boolean answer;
    
    /**
     * Creates new form AtomAskingWindow
     */
    public AtomAskingWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.answer = false;
    }
    
    public void setQuestion(String question){
        this.questionArea.setText(question);
    }

    public boolean getAnswer() {
        return answer;
    }

    public void setAnswer(boolean answer) {
        this.answer = answer;
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        questionAreaScroll = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yesButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        noButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        getContentPane().add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        questionArea.setColumns(20);
        questionArea.setRows(5);
        questionAreaScroll.setViewportView(questionArea);

        getContentPane().add(questionAreaScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 35, 310, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        this.setAnswer(true);
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        this.setAnswer(false);
    }//GEN-LAST:event_noButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noButton;
    private javax.swing.JTextArea questionArea;
    private javax.swing.JScrollPane questionAreaScroll;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
